name: PrimateAuth
version: '${project.version}'
main: ru.samsonium.primate.auth.PrimateAuth
api-version: '1.20'
commands:
  login:
    description: Авторизоваться в игре
    usage: /<command> <пароль>
  reg:
    description: Зарегистрироваться в игре
    usage: /<command> <пароль>
